# data parameters
experiment_name: 'local_equal_net'
dataset_name: retina # cifar10-mnist-mvtec-fashionmnist-retina
# training parameters
num_epochs: 201 # mvtec-Ad:601 Cifar10:201 MNIST:51
batch_size: 64
learning_rate: 1e-3

normal_class: 3  #'capsule' # mvtec: 'capsule' for retina:3


lamda: 0.01 #mvtec-Ad:0.5 Others:0.01

mvtec_img_size: 128

pretrain: True
use_bias: False
equal_network_size: False
direction_loss_only: False

# Test
localization_test: False # False: For Detection --- True: For Localization Test
localization_method: 'gbp' # gradients , smooth_grad , gbp
last_checkpoint: 10



